apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlflow
resources:
- ../../../base/mlflow
- ../../../base/rds-ca
components:
- ../../../components/mlflow-auth
patches:
- path: config.patch.yaml
configMapGenerator:
- name: mlflow-auth-policy
  files:
  - policy.json
  - checkpoints.json
